export const ADD_ITEM_CARRINHO = 'ADD_ITEM_CARRINHO';
export const REMOVE_ITEM_CARRINHO = 'REMOVE_ITEM_CARRINHO';
export const REMOVE_PRODUTO_CARRINHO = 'REMOVE_PRODUTO_CARRINHO';
export const SAVE_COMPRA = 'SAVE_COMPRA';
export const CLEAR_CARRINHO = 'CLEAR_CARRINHO';
export const CHANGEF0RMAPAGAMENTO = 'CHANGEF0RMAPAGAMENTO';